version: '3'
services:
  db:
    # postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
      # - app_postgre:/var/lib/postgresql/data #Windowsの場合
    environment:
      - POSTGRES_PASSWORD=password
    restart: always

    # mysql
    # image: mysql:8.0
    # volumes:
    #   - mysql-data:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    # environment:
    #   MYSQL_ROOT_PASSWORD: password

    # 下記共通
    ports:
      - '3306:3306'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
  bundle:
      driver: local